# This file was generated, do not modify it. # hide
#hideall
    using Markdown
    println("\`\`\`\`\`html $(Markdown.htmlesc(raw""" <table id="tlayout">
  <tr valign="top">
    <td id="layout-menu">
      <div class="menu-category">jemdoc</div>
      <div class="menu-item"><a href="index.html" class="current">home</a></div>
    <div class="menu-category">topics</div>
      <div class="menu-item"><a href="/pub/menu1.html">Menu 1</a></div>
      <div class="menu-item"><a href="/pub/menu2.html">Menu 2</a></div>
      <div class="menu-item"><a href="/pub/menu3.html">Menu 3</a></div>
    </td>
    <td id="layout-content">
      <p> CONTENT HERE </p>
      <div id="footer">
        <div id="footer-text">
          Page generated by <a href="http://jemdoc.jaboc.net/">jemdoc</a>.
        </div>
      </div>
    </td>
  </tr>
</table>""")) \`\`\`\`\`")